insecure: true

googleApiKey: ${GOOGLE_API_KEY}
zomatoApiKey: ${ZOMATO_API_KEY}

#cityIdOverride: 1

refreshPeriodInSeconds: 30

logging:
  loggers:
    com.pwang.kings: INFO

database:
  driverClass: org.postgresql.Driver
  user: pwang
  url: jdbc:postgresql://localhost/pwang