insecure: true

googleApiKey: ${GOOGLE_API_KEY}
zomatoApiKey: ${ZOMATO_API_KEY}

cityIdOverride: 1

refreshPeriodInSeconds: 10

database:
  driverClass: org.postgresql.Driver
  user: pwang
  url: jdbc:postgresql://localhost/pwang